In [1]:
#panda is an open source library of python for data manipulation and analysis
#it works on structured data

In [2]:
import pandas as pd
pd.__version__

'2.2.3'

In [3]:
df = pd.DataFrame([1,2,3,4,5])
print(df)

   0
0  1
1  2
2  3
3  4
4  5

In [4]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

In [6]:
data = { 'Name':['Adarsh','Mohan','Ravi','Praveen'],
        'Age':[21,34,26,67],
         'Salary':[55000,34565,24000,70000]
    }

df = pd.DataFrame(data)
print(df)

      Name  Age  Salary
0   Adarsh   21   55000
1    Mohan   34   34565
2     Ravi   26   24000
3  Praveen   67   70000

In [8]:

df.head()#it will show 5 which is inbuilt

      Name  Age  Salary
0   Adarsh   21   55000
1    Mohan   34   34565
2     Ravi   26   24000
3  Praveen   67   70000

In [9]:
df.head(2)#you can also write inside it how much you want to see

     Name  Age  Salary
0  Adarsh   21   55000
1   Mohan   34   34565

In [10]:
df.tail(2)

      Name  Age  Salary
2     Ravi   26   24000
3  Praveen   67   70000

In [11]:
df.shape #it will show you how many rows and columns are in table

(4, 3)

In [12]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='object')

In [13]:
df.rename(columns={'Salary':'Salary(Rs)'}) #you can rename any column you want

      Name  Age  Salary(Rs)
0   Adarsh   21       55000
1    Mohan   34       34565
2     Ravi   26       24000
3  Praveen   67       70000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Salary  4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [15]:
df.describe() #it will give you just these things like count mean standar deviation etc

             Age        Salary
count   4.000000      4.000000
mean   37.000000  45891.250000
std    20.704267  20588.928406
min    21.000000  24000.000000
25%    24.750000  31923.750000
50%    30.000000  44782.500000
75%    42.250000  58750.000000
max    67.000000  70000.000000

In [18]:
#now we are going to save this table
#since it saved the column of the index also we are gonna remove it
df.to_csv('Sample_data.csv',index = False)